const CREATE_POST = "CREATE_POST";
const DELETE_POST = "DELETE_POST";
const UPDATE_POST = "UPDATE_POST";
const FETCH_ALL = "FETCH_ALL";

const AUTH = "AUTH";
const LOGOUT = "LOGOUT";

export { CREATE_POST, DELETE_POST, UPDATE_POST, FETCH_ALL, AUTH, LOGOUT};
